### ISSUE TITLE
Analyzer issuing multiple linter hints for generated files

### ISSUE THREAD

**Issue by KOGI** [google/protobuf.dart#369]
After generating dart files, the analyzer is issuing multiple hints. These lints can be disabled via analysis options, but that change will apply to the entire project, not just the generated files. If, for this reason, an author opts to keep these lints enabled, then his code will now fail checks employed by several package developers as part of their build pipelines as well as those employed by `dart.dev` itself.

This lib should stop generating code that violates the following linter rules:
* [Avoid const keyword](https://dart-lang.github.io/linter/lints/unnecessary_const.html)
* [Annotate overridden members](https://dart-lang.github.io/linter/lints/annotate_overrides.html)
* [Sort unnamed constructor declarations first](https://dart-lang.github.io/linter/lints/sort_unnamed_constructors_first.html)

**Comment by KOGI** [comment]
@sigurdm @jakobr-google @sgjesse @kevmoo @szakarias

**Comment by fzyzcjy** [comment]
Hi is there any updates?

**Comment by osa1** [comment]
We current generate these `ignore_for_file`s:

https://github.com/google/protobuf.dart/blob/5e1a422e39476884861a2137b0d7241315889299/protoc_plugin/lib/src/file_generator.dart#L634-L648

So const keyword and overridden member warnings should be suppressed. Constructors also seem to be renamed to fix the "unnamed constrs" warnings.

I think the latest release do not have the updated ignore list but this should be fixed with the next release.
