### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by rockerhieu** [google/protobuf.dart#417]
Dart 2.10+ has support for null safety. Protobuf should support this too: https://dart.dev/null-safety#enable-null-safety

**Comment by dave** [comment]
Yes, I've just been playing with the Flutter null safety experimental support, and getting the error:

```
test/pb/tests.pb.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.3
^^^^^^^^^^^^^^
```

**Comment by Kavantix** [comment]
Since null-safety allows us to explicitly communicate through the api that something can be null or not we should maybe consider changing the api a bit.
For instance, setting a field of a message to null could clear the field and instead of returning default values and having to check `hasX` we could just do `if (x != null) x......`

**Comment by iinozemtsev** [comment]
There is a null_safety branch in this repo now and first null safety version is published: https://pub.dev/packages/protobuf/versions/2.0.0-nullsafety.0

Changing an API to use nullable fields instead of `hasX` would contradict proto3 language spec, which says that unset fields should have default values: https://developers.google.com/protocol-buffers/docs/proto3#default, and make Dart protos inconsistent with other language generators (e.g. [Java](https://developers.google.com/protocol-buffers/docs/reference/java-generated#singular-fields-proto3)), which return default values for unset fields.

**Comment by Kavantix** [comment]
I just checked the swift implementation (since it is close to dart nnbd) and that indeed also has the same behaviour as the `nullsafety` branch of this package so scratch that idea (sadly).

Is there any reason why `hasX()` is a method instead of a getter: `hasX`?

**Comment by sigurdm** [comment]
> Is there any reason why hasX() is a method instead of a getter: hasX?

It was made before my time, but my guess is that it was probably a mistake introduced by copying the java interface.
Changing it now would break a lot of code.

**Comment by robojones** [comment]
Is this issue resolved by now?
Version v20.0.0 is released on pub.dev (https://pub.dev/packages/protoc_plugin).
The version introduces null-safety (although I'm a bit confused why there is no release or tag for this on GitHub).

**Comment by zicklag** [comment]
@robojones it looks like it is in the `null-safety` branch. I was just able to compile a protobuf for dart 2.14 with null safety using that branch and it looks like it works, but I haven't done a lot of testing yet.

**Comment by YeFei572** [comment]
it doesn't work...

**Comment by YeFei572** [comment]
any updates?

**Comment by zicklag** [comment]
I haven't been able to test or find anything. I decided to switch to flatbuffers for my use-case so I won't be looking any further  ( but null safety is work-in-progress there too ).

**Comment by sigurdm** [comment]
This was fixed in v. 2.0.0

**Comment by talksik** [comment]
how was this fixed? When I access a proto response, I see String instead of String?
