### ISSUE TITLE
Could not find a subcommand named "install" for "flutter pub".

### ISSUE THREAD

**Issue by palkerecsenyi** [google/protobuf.dart#484]
The protoc_plugin README file mentions a non-existent command (`flutter pub install`): https://github.com/dart-lang/protobuf/blob/master/protoc_plugin/README.md#how-to-build-and-use.

Furthermore, running the closest matching command (`flutter pub get`) does not create a `bin` directory for me. I don't know where to find this directory.

However, `pub global activate protoc_plugin` does work for me, but this isn't optimal as I'd like to include `protoc_plugin` in my pubspec.

```
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

**Comment by sigurdm** [comment]
Yeah - I think the Readme meant `pub get`.

To use protoc_plugin from your dev_dependencies you have to make a script that calls `dart run protoc_plugin` because the `--plugin=` option to protoc does not take a full command-line only a single executable.

For unix/macos you can do something like:

`tool/run_dart_protoc_plugin.dart`
```
#!/usr/bin/env dart

import 'dart:io';

Future<void> main() async {
  final p = await Process.start(
    Platform.resolvedExecutable,
    ['run', 'protoc_plugin'],
    mode: ProcessStartMode.inheritStdio,
  );
  exit(await p.exitCode);
}
```
Make the tool executable:
```
> chmod +x tool/run_protoc_plugin.dart 
```
Then to run protoc plugin: 
```
> protoc --plugin=protoc-gen-dart='tool/run_protoc_plugin.dart' --dart_out=lib/protos protos/test.proto
```

For windows the script would have to be a batch/powershell script invoking `dart run protoc_plugin`.
