### ISSUE TITLE
Protoreflect ?

### ISSUE THREAD

**Issue by gedw99** [google/protobuf.dart#490]
Is reflection supported ?

I am using golang protobuf which has it and would be useful in dart for a flutter project I am working on

**Comment by sigurdm** [comment]
You probably have to be more specific - what do you want to do?

Some things are supported. See `GeneratedMessage.info_`. It contains a lot of information about fields.

Also the generated `.pbjson.dart` files have the full descriptors of enums, messages and services - you can decode them and use that to do basically anything - though it would be quite manual.

**Comment by srikrsna** [comment]
I am looking for similar feature set as Go. To be specific I am looking for options support. I can't seem to find field options in `GeneratedMessage.info_`. Can that be added?

**Comment by gedw99** [comment]
https://github.com/jhump/protoreflect

and 

https://github.com/fullstorydev/grpcui

Makes it easy to do reflection at runtime .

**Comment by naturallymitchell** [comment]
I'm also looking into "[Reflection for Protocol Buffers: Dynamic Messages and Stubs](https://github.com/jhump/protoreflect#dynamic-messages-and-stubs)" for Dart.

> The dynamic package provides a dynamic message implementation. It implements proto.Message but is backed by a message descriptor and a map of fields->values, instead of a generated struct. This is useful for acting generically with protocol buffer messages, without having to generate and link in Go code for every kind of message. This is particularly useful for general-purpose tools that need to operate on arbitrary protocol buffer schemas. This is made possible by having the tools load descriptors at runtime.
---

I also found [SquareAlfa Dart Framework](https://gitlab.com/squarealfa/dart_framework), which has [proto_annotations](https://pub.dev/packages/proto_annotations) and [proto_generator](https://pub.dev/packages/proto_generator), but it would seem better to use this library.  Or, since I'm going to use this within [Hetu](https://github.com/hetu-script/hetu-script), it may make sense to do it natively, like [protobuf.js](https://github.com/protobufjs/protobuf.js) or [protobuf-ts](https://github.com/timostamm/protobuf-ts).

**Comment by osa1** [comment]
Reflection is supported with `BuilderInfo` (`GeneratedMessage.info_` field). If `BuilderInfo` does not cover your use case please feel free to reopen with a concrete example of what you want to do.

**Comment by arkadiyt** [comment]
> Also the generated .pbjson.dart files have the full descriptors of enums, messages and services - you can decode them and use that to do basically anything - though it would be quite manual.

@sigurdm is there a copy of the FileDescriptor anywhere?

**Comment by sigurdm** [comment]
The canonical source is here I believe: https://github.com/protocolbuffers/protobuf/blob/c78b18960966e95201b6cac4e37fbf71d7e87dbf/src/google/protobuf/descriptor.proto

**Comment by arkadiyt** [comment]
@sigurdm I meant, is protoc-gen-dart embedding the file descriptor into the generated code, similar to how golang does, for reflection purposes? You mention above that some of the other descriptors are, but I don't see the FileDescriptor

**Comment by sigurdm** [comment]
Ah - sorry - misunderstood that completely :)

I don't think we currently do. You can file a new issue with the feature request.
