### ISSUE TITLE
Missing release for null-safety

### ISSUE THREAD

**Issue by robojones** [google/protobuf.dart#491]
Null-safety support was requested in #417 and seems to be supported in the latest version.
Although version 20.0.0 is released on pub.dev (https://pub.dev/packages/protoc_plugin), there is no release for it on GitHub.
Can you please create a tag and release for it?

**Comment by zaq1tomo** [comment]
I'm hoping for a null safety version of the release tag on GitHub, are there any plans to resolve this issue?

**Comment by osa1** [comment]
We have the tags ([protoc_plugin-v20.0.0][protoc_tag], [protobuf-v2.0.1][protobuf_tag]) but we don't have releases for those tags yet.

I'm curious because I've never needed to use a release on GitHub repo of a library (I used commits, tags), could you say a few words on how you use the releases? Are you downloading the source code as .zip or .tar.gz maybe?

I will be looking into making releases with these tags. Probably just a matter of clicking to "Create release from tag" buttons in the tags and copying changelog entries to release pages. 

[protoc_tag]: https://github.com/google/protobuf.dart/releases/tag/protoc_plugin-v20.0.0
[protobuf_tag]: https://github.com/google/protobuf.dart/releases/tag/protobuf-v2.0.1

**Comment by robojones** [comment]
I was using a [docker image](https://github.com/rvolosatovs/docker-protobuf) which has protoc and a few protoc plugins for different languages installed. The maintainer has his build set up so it installs the plugins via the zip archive which is attached to each release. This means that the plugin can be installed into the image using curl or wget. I wanted to create a pull request on his repository to bump dart protoc plugin to 20.0.0, without adding any special logic to the build script only to install the dart protoc pugin. By now, I have just setup my [own nightly image build](https://github.com/robojones/protoc-dart) which installs the plugin from pub.dev.

I still think it would be a good idea to create a proper GitHub release because there are probably more people using this install method. Also, since there are some releases present on this repository, it is confusing that there is none for the latest version.

**Comment by osa1** [comment]
I created releases for latest published versions of the plugin and the library:

- protoc_plugin: https://github.com/google/protobuf.dart/releases/tag/protoc_plugin-v20.0.0
- protobuf: https://github.com/google/protobuf.dart/releases/tag/protobuf-v2.0.1

Changelogs include changes since the last releases on GitHub.

We're also looking into automating the process so that every release on pub.dev will have a release on GitHub and a tag. We have #286 for that so I think it's safe to close this one now.
