### ISSUE TITLE
Something to suggest about guide

### ISSUE THREAD

**Issue by zizaihuan** [google/protobuf.dart#529]
1. tip that "we should use protoc_plugin"
![image](https://user-images.githubusercontent.com/43963067/126896543-0bc2e509-9dd0-4713-b53f-9b4e9846e440.png)
In https://pub.dev/packages/protobuf, there are five urls, but not one is https://pub.dev/packages/protoc_plugin.
Add some words link to https://pub.dev/packages/protoc_plugin, first, please. So we can find that we should use protoc_plugin quickly and then we will use "dart pub global activate protoc_plugin".

2. it's hard to find the path of  "the dart executable"
![image](https://user-images.githubusercontent.com/43963067/126896789-c442feb8-c153-4867-9d68-642deda0bcf4.png)

I am happy when I have confirm that both the dart executable and bin/protoc-gen-dart are in the path, however, when I use 
protoc --cpp_out=./cpp --dart_out=./dart try.proto
it tips that these is not "pub" command.
Then I guess if it means the "dart pub" or "flutter pub"?
So I add these path to system path, in flutter\bin\cache\dart-sdk\bin.
![image](https://user-images.githubusercontent.com/43963067/126896999-990569ed-a2a1-461d-8c0a-6661a9525598.png)
There is a dart.exe and pub.bat, and it works.

So now I know that "the dart executable" is not what I think first in flutter\bin, but the one "dart.exe" in  flutter\bin\cache\dart-sdk\bin.
![image](https://user-images.githubusercontent.com/43963067/126897078-70b4021c-720a-4c31-a390-06b221669e0f.png)

So I suggest it's better to tip that add flutter\bin\cache\dart-sdk\bin to path, which is hard to find.

Thanks.

**Comment by osa1** [comment]
Thanks for reporting this @zizaihuan. I started working on this project recently and I also found instructions for protoc_plugin a bit confusing. I will try to improve the README.

> I am happy when I have confirm that both the dart executable and bin/protoc-gen-dart are in the path, however, when I use
> protoc --cpp_out=./cpp --dart_out=./dart try.proto
> it tips that these is not "pub" command.

Could you show us the full error? This can happen in two cases:

1. You're using an old version of `protoc_plugin` that uses `pub` instead of `dart pub`.
2. You're using an old version of Dart that doesn't have the `dart pub` command and you're expected to use just `pub`.

Since you needed to create a `pub.bat` file to work around the issue, the problem you're facing must be (2) and you should update your Dart installation.

> So I suggest it's better to tip that add flutter\bin\cache\dart-sdk\bin to path, which is hard to find.

This is related to Dart or Flutter installation instructions. I suggest filing this as an issue to Dart or Flutter issue tracker if the instructions for installing Dart or Flutter is not clear.

**Comment by osa1** [comment]
@zizaihuan I tried to address some of your points in #610. If you could give feedback that would be appreciated.
