### ISSUE TITLE
Consider some extension member magic to avoid API noise in generated classes

### ISSUE THREAD

**Issue by kevmoo** [google/protobuf.dart#793]
![image](https://user-images.githubusercontent.com/17034/213319534-693e1bb6-214d-45b5-8658-0724ee231b6f.png)

Could we move most of the instance members of `GeneratedMessage` to extensions?

They add SO MUCH NOISE to API docs – and just general auto-complete for end users.

As it stands, publishing a package of generated APIs using grpc.dart would be less than ideal.

CC @osa1 @mraleph

**Comment by kevmoo** [comment]
I'd also like to understand the need for:

* `info_`
* `has*` and `clear*`

Trying to understand how often these are really needed by humans using the generated API

**Comment by mraleph** [comment]
We should probably just mark all of these methods with `@nodoc`.  We need to be careful with making them extensions - this can increase JS code size because static invocations are longer than method invocations. 

> `has*` and `clear*`

These are kinda part of a "canonical" protobuf API. Though I would expect generator to generate less "hazzers" for proto3 variant (as described here: https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md).

**Comment by osa1** [comment]
These are already marked as `@nodoc`, we just need to publish a new version.

https://github.com/google/protobuf.dart/blob/cc0f287fb6a8680e431eb9210225f1d0ac33c047/protobuf/lib/src/protobuf/generated_message.dart#L405-L471

**Comment by osa1** [comment]
This was fixed with protobuf-3.0.0.
